server:
  port: 8200

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://localhost:3306/cred_db
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation: none

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
