server:
  port: 8200

spring:
  application:
    name: authserver

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
