server:
  port: 8085

spring:
  application:
    name: authserver

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
