server:
  port: 8761

spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: discovery
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: '*'