server:
  port: 8083

spring:
  application:
    name: gateway

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
    resource-server:
      path: /resource-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8084
    authserver:
      path: /authserver/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8085
       
hystrix:
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
